import assert from 'node:assert/strict';
const base = process.env.TEST_BASE || 'http://127.0.0.1:3000';
const form = o => new URLSearchParams(o);
let r = await fetch(base+'/admin/dashboard', { redirect:'manual' }); assert.equal(r.status,302); assert.ok(r.headers.get('location').startsWith('/admin/login'));
r = await fetch(base+'/login', { method:'POST', headers:{'content-type':'application/x-www-form-urlencoded'}, body:form({email:'customer@novacapital.test',password:'Customer#2026!'}), redirect:'manual' });
const customerCookie = r.headers.get('set-cookie'); assert.ok(customerCookie);
r = await fetch(base+'/admin/dashboard', { headers:{cookie:customerCookie}, redirect:'manual' }); assert.equal(r.status,302, 'customer session cannot access admin');
r = await fetch(base+'/admin/login', { method:'POST', headers:{'content-type':'application/x-www-form-urlencoded'}, body:form({email:'admin@novacapital.test',password:'Admin#2026!'}), redirect:'manual' });
assert.equal(r.status,302); const adminCookie = r.headers.get('set-cookie'); assert.ok(adminCookie.includes('admin_sid='));
r = await fetch(base+'/admin/dashboard', { headers:{cookie:adminCookie} }); assert.equal(r.status,200); assert.ok((await r.text()).includes('Control Center'));
const email = `adjust${Date.now()}@example.test`;
r = await fetch(base+'/register', { method:'POST', headers:{'content-type':'application/x-www-form-urlencoded'}, body:form({name:'Adjust Target',email,phone:'+15550999999',password:'Password#2026',confirmPassword:'Password#2026'}), redirect:'manual' }); assert.equal(r.status,302);
r = await fetch(base+`/admin/balances?q=${encodeURIComponent(email)}`, { headers:{cookie:adminCookie} }); let html = await r.text(); assert.equal(r.status,200); const csrf = html.match(/name="_csrf" value="([^"]+)/)[1]; const accountId = html.match(/action="\/admin\/balances\/([^"]+)\/adjust\/preview"/)?.[1]; assert.ok(accountId);
r = await fetch(base+`/admin/balances/${accountId}/adjust`, { method:'POST', headers:{cookie:adminCookie,'content-type':'application/x-www-form-urlencoded'}, body:form({action:'ADMIN CREDIT',amount:'5000',reason:'Account funding',confirm:'YES'}), redirect:'manual' }); assert.equal(r.status,403, 'CSRF required for balance adjustment');
r = await fetch(base+`/admin/balances/${accountId}/adjust`, { method:'POST', headers:{cookie:adminCookie,'content-type':'application/x-www-form-urlencoded'}, body:form({_csrf:csrf,action:'ADMIN CREDIT',amount:'5000',reason:'Account funding',confirm:'YES'}), redirect:'manual' }); assert.equal(r.status,302);
r = await fetch(base+`/admin/balances?q=${encodeURIComponent(email)}`, { headers:{cookie:adminCookie} }); html = await r.text(); assert.ok(html.includes('Balance history')); assert.ok(html.includes('$5,000.00'));
r = await fetch(base+'/admin/exchange-rates', { headers:{cookie:adminCookie} }); html = await r.text(); const rateCsrf = html.match(/name="_csrf" value="([^"]+)/)[1]; const rateId = html.match(/action="\/admin\/exchange-rates\/([^"]+)"/)[1];
r = await fetch(base+`/admin/exchange-rates/${rateId}`, { method:'POST', headers:{cookie:adminCookie,'content-type':'application/x-www-form-urlencoded'}, body:form({_csrf:rateCsrf,buy_rate:'1421',sell_rate:'1451',fee:'2.50',status:'enabled'}), redirect:'manual' }); assert.equal(r.status,302);
r = await fetch(base+'/admin/rate-history', { headers:{cookie:adminCookie} }); assert.equal(r.status,200); assert.ok((await r.text()).includes('Rate History'));
r = await fetch(base+'/fx?amount=100&from=USD&to=KES&buy_rate=1'); const fx=await r.text(); assert.ok(!fx.includes('100 KES'), 'browser-supplied price ignored');
console.log('Security tests passed');
